[workspace]
channels = ["https://prefix.dev/conda-forge"]
description = "Showcases how to build a rust project with pixi"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
rust_bindings = { path = "." }
pytest = ">=8.3.5,<9"

[tasks]
test = "pytest"

[package]
description = "Showcases how to build a rust project with pixi"
name = "rust_bindings"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"]

[package.host-dependencies]
maturin = "*"
python = "3.12.*"
