[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
python = "3.12.*"
cpp_bindings = { path = "." }

[tasks]
start = "python -c 'import cpp_bindings as b; print(\"Here you go: 1 + 2 = \" + str(b.add(1, 2)))'"

[package]
name = "cpp_bindings"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.1.*" }

[package.build.configuration]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"]

[package.host-dependencies]
cmake = "3.20.*"
nanobind = "2.4.*"
python = "3.12.*"
